version: '3.8'

services:
  timeline:
    init: true
    image: schmelczera/timeline
    networks:
      - network
    ports:
      - target: 80
        protocol: tcp
        mode: ingress
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.5'
          memory: 32M
        reservations:
          cpus: '0.2'
          memory: 32M
      placement:
        max_replicas_per_node: 1
      update_config:
        parallelism: 1
        failure_action: rollback
        delay: 10s
        monitor: 10s
      restart_policy:
        condition: on-failure
        window: 30s

networks:
  network:
