name: Check formatting and lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Restore dependencies
        run: dotnet restore
      - name: Lint
        run: |
          npm ci
          npm run lint

          git diff
          if [[ `git status --porcelain` ]]; then
            exit 1
          fi
